### ISSUE TITLE
How to use Centos or Amazon Linux instead of Ubuntu?

### ISSUE THREAD

**Issue by VivekShingala** [gaiterjones/docker-magento2#2]
Hi 

Thank you for this wonderful repository.

I want to use Centos or Amazon Linux instead of Ubuntu with this repository. How can I replace Ubuntu with Centos?

**Comment by gaiterjones** [comment]
If you want to change the base operating system of the containers you would need to rebuild all the containers with the correct dependencies for that distribution of linux.

If you are talking about the host operating system then that is irrelevant as long as you can run Docker on it, the images should work.

**Comment by VivekShingala** [comment]
Hi @gaiterjones 

Thanks for the response.

I need to change the base operating system of the containers.

**Comment by gaiterjones** [comment]
You will need to build your own containers based on the container os you want to use.
