### ISSUE TITLE
Mac Docker File Share issue

### ISSUE THREAD

**Issue by jpratt** [gaiterjones/docker-magento2#7]
Trying to get this running on a mac. I am getting the following with the docker-compose up -d step:

Error response from daemon: Mounts denied:
The path /home/docker/data/magento2/mysql is not shared from the host and is not known to Docker.

I did have to change the varnish version in the docker-compose.yml to use version 7 as 6 was throwing an error when trying to download the image.

**Comment by jpratt** [comment]
Sorry, found the issue to change the path. But probably a good FYI on the docs and the varnish version.

**Comment by gaiterjones** [comment]
Thanks for pointing that out. The volumes are there to persist data and can either be commented out or used by setting the path in .env
