### ISSUE TITLE
Varnish is unable to resolve host name `shop01_magento2_php-apache_1`

### ISSUE THREAD

**Issue by MarcoMiltenburg** [gaiterjones/docker-magento2#8]
The Varnish 7 configuration file at `magento2/varnish/varnish7.vcl` contains a hard coded host name `"shop01_magento2_php-apache_1"` which can not be resolved:

```
backend apache_1 {
    .host = "shop01_magento2_php-apache_1";
    .port = "80";
...
}
```

The Varnish 6 file contains the name `"php-apache"` for the `.host` which I think should work. I replaced it with the hostname `magento2` of the `php-apache` service which worked for me.

**Comment by gaiterjones** [comment]
Thanks for pointing this out - this was a mistake, I will update the vcl.
