### ISSUE TITLE
Varnish configuration files contains hardcoded hostname `magento2.dev.com`

### ISSUE THREAD

**Issue by MarcoMiltenburg** [gaiterjones/docker-magento2#9]
Both Varnish 6 and 7 files contain the hardcoded hostname `magento2.dev.com` in the `backend` -> `.probe` -> `.request` section:

```
backend apache_1 {
    .host = "php-apache";
    .port = "80";
    .first_byte_timeout = 180s;
	.probe = {
	    .request =  "GET /health_check.php HTTP/1.1"
	                "Host: magento2.dev.com"
	                "Connection: close"
	                "Accept: text/html" ;
	    .timeout  = 60s;
	    .interval = 120s;
	    .window    = 10;
	    .threshold = 8;
	}
}
```

This should be replaced with the correct hostname based on the `.env` file upon copying it to the image.

**Comment by gaiterjones** [comment]
Yes, you must update the vcl with the hostname you are using for the installation otherwise varnish will show a health error.
